spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library-mngt
    username: unchk
    password: unchk@2025
    hikari:
      auto-commit: false

  banner:
    location: banner

security:
  rsa:
    public-key: classpath:certificates/public.pem
    private-key:  classpath:certificates/private.pem
  cors:
    allowed-origins:
     - http://localhost:4200
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS

  token:
    issuer: LMA Authentication & Authorization
    delay: 1
    test:
      header: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJKQUQgQXV0aGVudGljYXRpb24gJiBBdXRob3JpemF0aW9uIiwic3ViIjoiamFkLnN5c3RlbUBnbWFpbC5jb20iLCJleHAiOjE3NDA1NTU0MjksImlhdCI6MTc0MDQ2OTAyOSwiZW1haWwiOiJqYWQuc3lzdGVtQGdtYWlsLmNvbSIsInNjb3BlIjoiU1lTVEVNIn0.optZjdnJsrJCeXCrDpG41C0RjH7-9ZkHHZQ433-_Kd3kUQzsINOrPmzPtjWSzADlRPbeuuNSaV0p7_bqwAGr2-zDP25UT-pokjQY6GQ4cGtBO5bwY-uFRKmN94NZN_01GJKyI_huqRDLzCOAj12cDT6AdZe9VNG8h-JIG1WH0TE2KCFDxTPzpS3cGjWuqfW1nYgGhc5wYAKJdrQ15RrFTp_A78XvdwjvBguoFhhDpWmzQj_cxcA8Wg3B0TAJ-EHnuC6TvfhIAlvZB9LbJaTijK-R6-YUoi-O9cbULACLo_LVTEggMVsB1wVr-ISiJmZZ2iCgQ6rGIVnsZO6d-j6sfl6hV9IKCAApa8jpRAAi2vUP_2_EksD4e9PJxQ-Q-yPVhTNEB6yceqcUEjKXdgaoaxZJ3ugO3oq2YmsZcXxFIdzATbf3xqzV27SvQvH8K8bJSkcCcWcbV_gSD9L8HrI-K_G8EqeIO_-mQmNhUvKHMY5s0t9Vj6buB7ZlS1nrdN51GJ6hugfHsn5NtPVRyf45uIx64cKLhynK58NfCG5cBib5vqmKbIHYj55UUJz216t4QFlwFyqd8HSIm3_p7VLq_wzFewlpbGzg7DInjwlcW5Ki4TIfX-zQNDdzsaHhxzKW3xEc3n0tqy8eO6iTl2_YO7U0KWyzoJQeSk93smZUiEQ

application:
  url: http://localhost:${server.port}